name: Playwright Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    timeout-minutes: 15
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-node@v4
      with:
        node-version: 22.13.0
    - name: Create env file
      run: |
        touch .env
        echo MAILOSAUR_API_KEY=${MAILOSAUR_API_KEY} >> .env
        echo MAILOSAUR_SERVER=${MAILOSAUR_SERVER} >> .env
      env: 
        MAILOSAUR_API_KEY: ${{ secrets.MAILOSAUR_API_KEY }} 
        MAILOSAUR_SERVER: ${{ secrets.MAILOSAUR_SERVER }} 
    - name: Install dependencies
      run: npm install -g pnpm && pnpm install
    - name: Install Playwright Browsers
      run: pnpm test:browsers
    - name: Run Playwright tests
      run: pnpm test:ci
    - name: Test Report
      uses: dorny/test-reporter@v2
      if: success() || failure()
      with:
        name: Tests
        path: junit.xml
        reporter: jest-junit
    - uses: actions/upload-artifact@v4
      if: ${{ !cancelled() }}
      with:
        name: playwright-report
        path: playwright-report/
        retention-days: 30
